---
title: "scFPCDE-overview"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{scFPCDE-overview}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#"
)
```

```{r setup}
library(scFPCDE)
library(ggplot2)
```

## Simulated Example Data

```{r simulate}
data(scFPCDE_simdata)
yt <- scale(scFPCDE_simdata$yt)
tt <- scFPCDE_simdata$tt
```

## Run FPCA-DE Pipeline

```{r run}
res <- scFPCDE_run(yt, tt)
```

## P-Value Distribution for D-statistic Test

```{r pval}
hist(res$D_test$p_value, breaks = 40,
     main = "P-value Distribution (D-test)",
     xlab = "P-value", col = "gray")
```

## Contingency Table of DE Detection vs. Oracle

```{r contingency}
DE_ids <- rep(c(1, 0), c(100, 400))
table(DE_ids, res$D_test$p_value < 0.05, 
      dnn = c("Oracle", "Test Result"))
```

## Gene Expression Curve Visualization for Top DE Genes

```{r plot}
top_degs <- order(res$D_test$D_obs, decreasing = TRUE)[1:12]
scFPCDE_gene_curves(
  tt = tt,nrow = 3, ncol = 4, 
  yt = yt,
  yt_fit = res$fpca_result$xt_hat,
  cell_cluster = scFPCDE_simdata$clusters,
  subset = top_degs
)
```
